### ISSUE TITLE
Dockerfile instructions are somewhat broken

### ISSUE THREAD

**Issue by tlater-famedly** [famedly/ldap-sync#11]
See https://github.com/famedly/ldap-sync/pull/8#discussion_r1698481630_

At face value, this should not be working, but does in practice.

**Comment by sirewix** [comment]
Apparently the `PROJECT_NAME` is set in the builder container but not in the target container, thus `COPY` command copies all `/app/target/release/` contents into `/usr/local/bin/`

**Comment by sirewix** [comment]
Also, the `release/` dir contains all the build artifacts (for `debug` on my machine it's ~5G now)
