### ISSUE TITLE
Users with non-canonical phone numbers cannot be synced

### ISSUE THREAD

**Issue by tlater-famedly** [famedly/ldap-sync#55]
Currently, users with phone numbers that Zitadel does not accept will fail to sync, as Zitadel validates phone numbers before importing users.

In practice, it seems most users do not specify valid phone numbers in LDAP, so we need to do something about this besides telling people to specify valid phone numbers.

The most reasonable approach is probably to check error messages to see if a user failed because of an invalid phone number, and if that happens immediately try to re-import the user, but without a phone number; Writing our own regex or copying Zitadels' risks drifting away from their exact implementation, which may cause failed syncs in the future, so even if we implement some kind of local check to prevent sending as many requests we should still do some kind of double sync.

**Comment by emgrav** [comment]
We could also add a configurable country code and attempt to canonicalize the phone numbers with the configured country code. While there will be edge cases, these should be limited to cases where 1) A user has a phone number from another country than their organization is in, and 2) This international phone number is missing a country code. While there will probably be quite a bit of the first, both of these being true at once seem unlikely.

**Comment by tlater-famedly** [comment]
Yeah, that is probably sensible if we want to ensure that all users that have phone numbers set actually get them synced; still, even if we canonicalize the phone numbers, we should handle cases where Zitadel doesn't like the phone numbers. They are explicitly optional, users should not fail to sync because their phone numbers are in an unexpected format.

**Comment by tlater-famedly** [comment]
We discussed this in the sync - @nikzen suggests that the phone number may even be internal to e.g. a hospital, rather than a "real" phone number, so we should not try to add a prefix in general. Simply adding a retry for this should be sufficient.
